/*
 * This file is generated by jOOQ.
 */
package com.qinyadan.system.dsp.storage.meta;


import com.qinyadan.system.dsp.storage.meta.tables.Columns;
import com.qinyadan.system.dsp.storage.meta.tables.Schemata;
import com.qinyadan.system.dsp.storage.meta.tables.Tables;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sloth extends SchemaImpl {

    private static final long serialVersionUID = -514278016;

    /**
     * The reference instance of <code>sloth</code>
     */
    public static final Sloth SLOTH = new Sloth();

    /**
     * The table <code>sloth.columns</code>.
     */
    public final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>sloth.schemata</code>.
     */
    public final Schemata SCHEMATA = Schemata.SCHEMATA;

    /**
     * The table <code>sloth.tables</code>.
     */
    public final Tables TABLES = Tables.TABLES;

    /**
     * No further instances allowed
     */
    private Sloth() {
        super("sloth", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Columns.COLUMNS,
                Schemata.SCHEMATA,
                Tables.TABLES);
    }
}
