/*
 * This file is generated by jOOQ.
 */
package com.qinyadan.system.dsp.engine.meta;


import com.qinyadan.system.dsp.engine.meta.tables.Columns;
import com.qinyadan.system.dsp.engine.meta.tables.Schemata;


/**
 * Convenience access to all tables in sloth
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>sloth.columns</code>.
     */
    public static final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>sloth.schemata</code>.
     */
    public static final Schemata SCHEMATA = Schemata.SCHEMATA;

    /**
     * The table <code>sloth.tables</code>.
     */
    public static final com.qinyadan.system.dsp.engine.meta.tables.Tables TABLES = com.qinyadan.system.dsp.engine.meta.tables.Tables.TABLES;
}
